### ISSUE TITLE
Using Keen's AutoCollector

### ISSUE THREAD

**Issue by codasana** [maxpaj/vue-keen-tracking#1]
I have a nuxt project and would like to use this library in it. 

I want to use it for tracking all page views. Keen provides an autocollector function client.initAutoTracking();

How can I use that in my Nuxt/Vue project using this library. 

In my Vuex store, I have a user object. So, I would like to extend keen with the user object and then record all page views. Can you please help?

**Comment by maxpaj** [comment]
I'm looking into this. See if there is a way to nicely integrate with Vuex actions / mutations. I'll also look into how to integrate with vue-router.

**Comment by maxpaj** [comment]
You should be able to access `this.$keen.extendEvents(() => { user })` at the point where you fetch your user object.

**Comment by maxpaj** [comment]
https://github.com/maxpaj/vue-keen-tracking/pull/2 added `autoCollector: true` to the config of the plugin. Updated README, you can check it out.

**Comment by codasana** [comment]
This is great. I will update and try. Keen allows you to modify what's collected with autoCollector. Where can I change that?

Also, in a component lifecycle, where should I add 'Record' so that an event occurs on every page load. For example, I tried putting it in a Footer component in 'mount'. But if a page changes, I think because the footer component doesn't reload, the event doesn't trigger. What could be the right place for it?

**Comment by maxpaj** [comment]
> This is great. I will update and try. Keen allows you to modify what's collected with autoCollector. Where can I change that?
> 
> Also, in a component lifecycle, where should I add 'Record' so that an event occurs on every page load. For example, I tried putting it in a Footer component in 'mount'. But if a page changes, I think because the footer component doesn't reload, the event doesn't trigger. What could be the right place for it?

Ah yes, you can pass those options with `autoTracking: { recordPageViews: true, ... }`. I updated the README.

**Comment by maxpaj** [comment]
If you're using Nuxt in SPA mode, I think you should attach the `vue-router` integration to the plugin to track page views / router changes. Since you're using `vuex` I'm assuming you are using SPA mode, but maybe I'm wrong. Can you explain a bit more how you're using Nuxt?

**Comment by maxpaj** [comment]
@msahajwani 

Closing this one, open it up again if you feel like it hasn't been taken care of.
